<a href="https://colab.research.google.com/github/dl-ub-summer-school/2021/blob/main/seminar1/seminar1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<table class="buttons" align="center">
    <td>
        <a target="_blank" href="https://colab.research.google.com/github/dl-ub-summer-school/2021/blob/master/seminar1/seminar1.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Google Colab дээр нээх</a>
    </td>
    <td>
        <a target="_blank" href="https://github.com/dl-ub-summer-school/2021/blob/master/seminar1/seminar1.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />GitHub дээр нээх</a>
    </td>
    <td>
        <a target="_blank" href="https://sites.google.com/view/dlub"><img src="https://avatars0.githubusercontent.com/u/52651086?s=32&v=4">Зуны сургалтын вебсайт</a>
    </td>
</table>

In [ ]:
import torch
import random
import numpy as np
from sklearn.datasets import make_regression
from torch.utils.data import Dataset, DataLoader, random_split

# Intro to Pytorch and tensors

## Initializing tensors and operations on tensors

In [ ]:
# Initializing emtpy matrix

x = torch.rand(5, 3)
print(x)
# Initializing random matrix

# Accessing element
print(x[4,2])
# Size

# Operators

## Adding

## Element wise multiplication

## Element wise division

## changing shape

tensor([[0.9063, 0.9389, 0.1697],
        [0.4062, 0.9414, 0.8867],
        [0.1088, 0.6782, 0.8232],
        [0.8828, 0.1779, 0.5482],
        [0.7369, 0.6923, 0.0397]])
tensor(0.0397)


In [ ]:
print(x.size())

torch.Size([5, 3])


In [ ]:
y = torch.rand(5,3)

In [ ]:
x * y

tensor([[0.4165, 0.3359, 0.1496],
        [0.3316, 0.3648, 0.6268],
        [0.0566, 0.1764, 0.7073],
        [0.3733, 0.1163, 0.0076],
        [0.5378, 0.2885, 0.0016]])

In [ ]:
torch.mm(x.t(), y)

tensor([[1.7159, 1.3939, 1.2223],
        [2.1336, 1.2819, 2.1070],
        [1.4913, 0.9932, 1.4930]])

In [ ]:
x = torch.rand(5, 10, 4, 7)

In [ ]:
x[0:-1, 5:10, :, 1:3].size()

torch.Size([4, 5, 4, 2])

In [ ]:
x = torch.rand(5, 4)

In [ ]:
x1 = x.view(-1, 10)
print(x1.size())

torch.Size([2, 10])


## Tensor slicing

In [ ]:
# x = torch.rand(5, 3, 30)
# print(x.size())
# print(x[1:5, :, 4:10].size())
# print(x[1:5, :, 4:-1].size())

torch.Size([5, 3, 30])


## Matrix multiplication

In [ ]:
m = torch.mm(x, y.transpose(0, 1))

#m = torch.mm(x.transpose(0, 1), y)

print(m)
print(m.size())

In [ ]:
# x = torch.rand(5, 4)
# y = torch.rand(4, 3)

# print(x.mm(y).size())

# Text => Numbers (Word embedding)

## One hot Encoding

In [ ]:
# sentence to vector
sentence = "The dog barked in the park. The owner of the dog put him on the leash since he barked."
words = []
for s in sentence.lower().split(" "):
  words.append(s.strip("."))

In [ ]:
vocab = ["UNK", "the", "dog", "park", "barked", "he", "is", "put", "owner"]

In [ ]:
vocab2idx = {x: i for i, x in enumerate(vocab)}

In [ ]:
def word2onehot(word):
  pos = vocab2idx.get(word, 0)
  one_hot = [0] * len(vocab)
  one_hot[pos] = 1
  return one_hot

In [ ]:
onehot = []
for w in words:
  onehot.append(word2onehot(w))

In [ ]:
tensor_onehot = torch.tensor(onehot)
print(tensor_onehot)

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0]])


In [ ]:
# Exercise: Calculate co-occurence.

# Linear regression

## Data loading

In [ ]:
class ToyDataset(Dataset):
    """Sample dataset for regression."""

    def __init__(self, feature_count=2, sample_count=100):
        self.X, self.y = make_regression(
            n_samples=sample_count, n_features=feature_count, 
            noise=0.1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [ ]:
# Create dataset and split
full_dataset = ToyDataset(sample_count=100, feature_count=2)

print("All data", len(full_dataset), full_dataset.X.shape)

All data 100 (100, 2)


In [ ]:
train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size

train_dataset, test_dataset = random_split(
    full_dataset, [train_size, test_size])

In [ ]:
print(len(test_dataset))

20


## Regression

In [ ]:
class LinearRegression():
  def __init__(self, learning_rate=0.001, feature_count=2):
    # random theta
    self.alpha = learning_rate
    self.theta = np.random.randn(feature_count)
  
    
  def predict(self, X):
    """
    [
     [1,2],
     [2,3]
    ]
    """
#     for xx in X:
#       sum([xxi * t for xxi, t in zip(xx,self.theta)])
      
    return X.dot(self.theta)
    
  def calculate_loss(self, X, y):
    # sum(y_pred - y ^ 2)
    y_pred = self.predict(X)
    J = np.sum((y_pred - y) ** 2) / len(y)
    
    return J
  
  
  def grad(self, X, y):
    # sum(y_pred - y ^ 2)
    
    # sum(2*(y_pred - y)*deriv_y_pred) / m
    
    # y_pred = theta * X => deriv_y_pred = X
    
    # y_pred - y
    err = self.predict(X) - y
    gradient = 2 * X.T.dot(err) / len(y)
    return gradient
  
  
  def fit(self, X, y, epochs=5):
    # loop through epochs
    for e in range(epochs):
      gradient = self.grad(X, y)
      
      # update params
      self.theta = self.theta - self.alpha * gradient
      
      if e % 1000 == 0:
        print("Loss", e, ":", self.calculate_loss(X, y))

In [ ]:
# Model & test
model = LinearRegression(feature_count=2, learning_rate=0.1)

X_test, y_test = test_dataset[:]

In [ ]:
print(model.calculate_loss(X_test, y_test))
for y_true, y_pred in zip(y_test, model.predict(X_test)):
  print(f'Y: {y_true:.2f}, Y pred: {y_pred:.2f}')

In [ ]:
X_train, y_train = train_dataset[:]
model.fit(X_train, y_train, epochs=4001)


Loss 0 : 5864.276074715073
Loss 1000 : 0.007518441306127367
Loss 2000 : 0.007518441306127367
Loss 3000 : 0.007518441306127367
Loss 4000 : 0.007518441306127367
